mj:
  discord:
    guild-id: 1425743734011592706
    channel-id: 1425743734737469474
    user-token: MTQyMDY2ODE2NTMzOTQ4MDE0Ng.GS5Sie.AcXJg9PzyoBBKWB90I70M-0bCtdcrcRfNi8sI4
    user-agent: Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
    enable: true
    core-size: 3
    queue-size: 10
    timeout-minutes: 5

  task-store:
    type: in_memory
    timeout: 30d