server:
  port: 8080
  contextPath: /mj

logging:
  level: info

mj:
  taskStore:
    type: in_memory
    timeout: 30d
  accountChooseRule: BestWaitIdleRule
  accounts: []
  proxy:
    host: 
    port: 
  ngDiscord:
    server: 
    cdn: 
    wss: 
    resumeWss: 
    uploadServer: 
  baiduTranslate:
    appid: 
    appSecret: 
  openai:
    gptApiUrl: 
    gptApiKey: 
    timeout: 30s
    model: gpt-3.5-turbo
    maxTokens: 2048
    temperature: 0
  translateWay: null
  apiSecret: 
  notifyHook: 
  notifyPoolSize: 10

